import fr_dep_news_trf
import spacy

nlp = spacy.load("fr_dep_news_trf")
nlp = fr_dep_news_trf.load()

doc = nlp("2013 Mathis Zerbib Curriculum VitaehttpsmathiszerbibgithubioCvCvMathisindexhtml 12Mathis ZerbibDéveloppeur FullStackEmail mathiszerbibgmailcomIntroductionJe mappelle Mathis Zerbib je suis né à Nîmes en France et actuellement Freelance surla région de MontpellierSpécialisé en développement web et logiciels je peux concevoir des sites vitrinesstatiques aux applications web ou sites decommerce Tous mes sites sont réalisés demanière responsive adaptables à tous les appareilsJe travaille avec diverses technologies que je vous laisse découvrir dans mon cvNhésitez pas à me contacter pour de plus amples informationsMes experiencesDirecteur Technique Co fondateur de CastornauteAgence WebJuin 2019 Septembre 2019Agence digitale spécialisée dans le développement Web la création graphique et le WebMarketingDeveloppeur Web Zyneas Solutions RHFevrier 2019 Juin 2019Developpement de sites web en HtmlCssPhpJavaScript et de solutions RH Internes enNodeJsFreelanceFervrier 2018Commande de sites webs WordPress CMS Création dun portfolio dartiste etdéveloppement de differents sites vitrines Freelance Developpeur FullStack BSWEBOctobre 2017 Fevrier 2018Développement dune solution de récupération de données automatisé WebScrappingavec NightmareJs et ElectronJs Stagiaire Développeur WebAout Octobre 2017La société BSWEB mà permis dapprofondir mes connaissances dans le web et demaffirmer sur le marché de lemploi17032023 2013 Mathis Zerbib Curriculum VitaehttpsmathiszerbibgithubioCvCvMathisindexhtml 22Animateur BAFASeptembre 2015 Octobre 2016Animateur sur Nîmes et ses alentours jai eu des experience tant en ACM quen Classesvertes ou Colonies de vacances IFAC et Ligue de lEnseignementCompétencesMongoDBPhpPOOSQLJavaScriptAngularJs7ReactjsJenkins et DockerGoogle CloudTerminal Linux et WindowsFlutterScolaritéDéveloppeur LogicielObjectif 3W Obtenu avec mention Bien Diplôme développeur logiciel niveau IIIBaccalauréat section littéraire en Candidat LibreArrêt des cours en Terminale 2016 Après larrêt des mes cours je vais en Angleterre où je perfectionne mon Anglais pourainsi revenir par la suite et passer le bac en France")

print([(w.text, w.pos_) for w in doc])
