name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI_DIR: back

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # clone all submodules
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --prefix $CI_DIR  # Run npm ci inside the /frontend folder
      - run: npm run build --if-present --prefix $CI_DIR # Run npm build inside the /frontend folder
      - run: npm test --prefix $CI_DIR  # Run npm test inside the /frontend folder
